### PR TITLE
Safely quiet and shutdown sidekiq during deployments and shutdown

### PR DESCRIPTION
**Pull request by kpheasey**

### CODE REVIEW

**Comment by ajgon** [comment]
I like the idea, but can you please fix the tests and linters?

**Comment by kpheasey** [comment]
Sure thing.  I’ll see if I can get to it in the next 48 hours.

**Comment by ajgon** [comment]
Sure, no worries, thanks!

**Comment by kpheasey** [comment]
I need to make a few more commits to clean up the specs and test coverage.  I'll create a new pull request with a single squashed commit.

**Pull request closed without merging**
