### PR TITLE
feat(scm): Support configurable location of git_ssh_wrapper

### LINKED ISSUE #120: Support configurable location of git_ssh_wrapper
(Opening this issue to reference in a PR.)

As a devops person working in an environment such as a CIS Level 1 (or higher) hardened Linux server that has a separate `/tmp` directory with `noexec` settings, I would like the ability to specify a directory other than `/tmp` for the execution of the autogenerated Git SSH wrapper that is used for the deployment of private Git repos.

Acceptance criteria:
- New attribute `app[:scm][:generated_ssh_wrapper]` with default value `/tmp/ssh-git-wrapper.sh`
- The attribute `app[:scm][:ssh_wrapper]` still exists and defaults to whatever value of `app[:scm][:generated_ssh_wrapper]` was provided
- The SSH wrapper is generated if and only if `app[:scm][:generated_ssh_wrapper]` and `app[:scm][:ssh_wrapper]` have the same value, which is to say, only if the user of this cookbook has not overridden the `:ssh_wrapper` to point to a script that they have generated outside of the cookbook's purview.

With these behaviors in place, the caller of the cookbook can simply set `:generated_ssh_wrapper` to a value outside the `/tmp` partition, thus avoiding the `noexec` issue. Existing users of the `:ssh_wrapper` functionality will see no change in behavior, except that the cookbook will no longer create (and then not bother to use) the generated SSH wrapper during the deploy process.

### PR DESCRIPTION
**Pull request by nickmarden**
Fixes #120

### CODE REVIEW

**Comment by ajgon** [comment]
Maybe I'm missing something, but wasn't this a responsibility of `ssh_wrapper` configuration variable? So you could set `ssh_wrapper=/var/tmp/my-script.sh` or whatever, and this should be it (of course you would have to provide this script to your server via different cookbook).

**Comment by nickmarden** [comment]
> of course you would have to provide this script to your server via different cookbook

 I want all of your built-in infrastructure for generating a correctly-working `GIT_SSH_COMMAND`...It's good! But I don't want people, including me, to be (mis)handling management of sensitive keys in their cookbooks just because the location of the generated file doesn't work for them. I also don't want them to be digging around in the guts of the `aws_opsworks_app` data for this one bit of data (SSH keys) when the cookbook is already doing all of the rest of the digging (correctly and adaptable to future changes) for them.

So I want everything the cookbook already does to generate the wrapper, but I want specify where the cookbook creates it. (And, by the way, I agree that the current default is a reasonable one, because you know every system is likely to have a `/tmp` directory. It's just that some of us aren't allowed to exec stuff from there.)

If you're still in agreement with me at all, I'd ask ask you to consider my argument that this PR actually doesn't do much. It basically boils down to four things:

1. It gets rid of several places where `def out` was being defined as boilerplate `handle_output(raw_out)`
2. It clarifies the naming of the `raw_out` concept, which I always struggled with. `raw_out` really means "these are the settings for this driver, although some of them might not be visible to the templates instantiated by the driver". So I called it `settings`, which to me anyway is more intuitive. YMMV of course, and it's your cookbook.
3. It allows the `defaults` for a given setting to depend on the other settings for that driver, i.e. to be defined as a proc that gets evaluated at runtime. I can imagine this being useful for other features in the future.
4. Lastly, it implements the behavior described in #120, that `/tmp` should be overridable for people in hardened environments.

I hope you'll consider my approach in light of these comments.

Thanks!

**Comment by ajgon** [comment]
Oh, now I get it. 

Maybe, to avoid the confusion, we should rename those parameters? So, change `ssh_wrapper` to `custom_ssh_wrapper_path`? And the second one to `generated_ssh_wrapper_path` - so we will see in a blink of an eye, which parameter does what.

Other thant that - great PR, I really appreciate it 👍

**Comment by nickmarden** [comment]
I think `ssh_wrapper` is a setting that people might already be using, so I'm reticent to change its name.

If you'd like I can change `generated_ssh_wrapper` to `generated_ssh_wrapper_path`, but then that would be awkward because `ssh_wrapper` wouldn't be called `ssh_wrapper_path`.

Your call, I'll do whatever you want.

**Comment by ajgon** [comment]
Ok, let's keep it as is 👍

**Pull request merged**
