### PR TITLE
feat(setup): added support for webpacker

### PR DESCRIPTION
**Pull request by kpheasey**
Rails 5.2 adds webpacker support by default.  This PR adds necessary functionality to support webpacker.

# Features
* Significantly decrease asset compilation time for webpacker by adding symlinks for node_modules and public/packs
* Install Node.js 10.15.3 LTS
* Install latest Yarn

### CODE REVIEW

**Comment by kpheasey** [comment]
@ajgon Just wondering why this hasn't been merged yet, is there something that needs to be changed?

**Comment by ajgon** [comment]
@kpheasey - I believe we have unresolved discussion here - https://github.com/ajgon/opsworks_ruby/issues/80 - this change may break things, and I want to be sure that we can avoid it, the best way possible.

Have you battle tested this PR?

**Comment by kpheasey** [comment]
@ajgon I didn't notice the issue mentioned in #80.  I believe it's a non-issue and have responded there.

> Have you battle tested this PR?

Yes, I've been running it in production, on Ubuntu 16 and 18, for months.  Before I made the PR I had my own recipes that did the same thing.

**Comment by ajgon** [comment]
All right then - then the only remaining concern is making it configurable? Can you do that? If not, I can write something up basing on your PR.

**Comment by kpheasey** [comment]
@ajgon Not sure what you mean by configurable.  Any changes to node or yarn installation can be configured via normal attributes from the respective packages.

**Comment by ajgon** [comment]
@kpheasey Sorry, maybe I didn't make myself clear enough. What I meant, is configurable enabling/disabling of webpack/yarn at all. The point is - don't install whole nodejs ecosystem on the server if user doesn't need it (i.e. has Rails API only app).

**Comment by kpheasey** [comment]
@ajgon If you can base it off my PR that would be great.  Otherwise, just point me to an example of a current configurable (on/off) feature and I will work off that.

**Comment by ajgon** [comment]
Added the required option here: https://github.com/ajgon/opsworks_ruby/commit/25f501835071186a63558ecf4868a2a614fdd5b7 - thanks for wrapping this up!

Also [released a new version](https://supermarket.chef.io/cookbooks/opsworks_ruby) of the cookbook :)

**Pull request closed without merging**
