### PR TITLE
Add Shoryuken

### PR DESCRIPTION
**Pull request by johncalvinyoung**

### CODE REVIEW

**Comment by ajgon** [comment]
Why did you close it? Didn't work as expected?

**Comment by johncalvinyoung** [comment]
It was an internal WIP pull request. Not quite ready yet--opened here by accident. 

John Calvin

**Comment by johncalvinyoung** [comment]
@ajgon However, would it be possible to merge https://github.com/ajgon/dummy-app/pull/1 to support my development?

**Comment by ajgon** [comment]
Sure, but please, open a PR against different branch than master. Dummy-app has different branches, to support different configuration setups.

**Pull request closed without merging**
