### PR TITLE
Run `monit reload` only once, after `configure hook`

### PR DESCRIPTION
**Pull request by kzkn**
In order to avoid running `monit reload` multiple times in a row, I changed it to run `monit reload` only once after running the `configure` hook.

ref: #251

### CODE REVIEW

**Comment by kzkn** [comment]
The CI failure will probably be resolved by merging https://github.com/ajgon/dummy-app/pull/3

**Comment by kzkn** [comment]
Oops, it's failing for another reason :thinking: 
Is the docker pull failing? This is the first time I've encountered this error.

> 18.04: Pulling from library/ubuntu
> STDERR: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

@ajgon 
I don't think it has anything to do with my changes. Do you know how to resolve this?

**Comment by ajgon** [comment]
Your PR is fine, it was travis which had troubles. I re-ran the checks and all of them passed, except the "s3" one - which is expected, as I changed S3 keys for it, and your commit does not reflect that :)

I merged it manually to master, when travis turns green - I'll release a new version with your fix. Thank you!

**Comment by ajgon** [comment]
@kzkn Version 1.20.2 released with the fix. Thanks again!

**Comment by willkoehler** [comment]
Thanks @ajgon for getting this merged and released quickly 🙌

**Pull request closed without merging**
