### PR TITLE
feat(logrotate): support arbitrary logrotate customization

### LINKED ISSUE #107: Support arbitrary customization of logrotate configurations
As an opsworks_ruby user, I'd like to be able to configure any and all options related to logrotate generation for my application, so that I can deploy it an environment where the default `logrotate_app` behaviors in Drivers::Dsl::Logrotate would be deemed acceptable.

Implementation expectations:

* `node['deploy'][app_name][driver_type]['logrotate_name']` and `node['deploy'][app_name][driver_type]['logrotate_log_paths']` (`driver_type` =`framework` or `webserver`) can be used to override the framework- or webserver-level defaults for `logrotate_app` resource name, and `path` property, respectively. These two settings would *not* have `node['defaults']['global']`, `node['defaults'][driver_type]` or `node['deploy'][app_name]['global']` equivalent settings because it is meaningless to talk about a cookbook-wide or app-wide default for either setting; it must be an app+driver_type-level setting. The app+driver_type-level defaults for these two settings would continue to be `"#{app['shortname']}-#{adapter}-#{deploy_env}"` and whatever is set via the class method `.log_paths`, respectively.
* As a special case, setting `node['deploy'][app_name][driver_type]['logrotate_log_paths']` to an empty array (`[]`) will disable logrotate file generation for that app+driver_type.
* Any other setting _X_ related to logrotate can be configured by setting one of the four following settings, in the following order from highest to lowest precedence:
  - `node['deploy'][app_name][driver_type]['logrotate_X']`
  - `node['deploy'][app_name]['global']['logrotate_X']`
  - `node['defaults'][driver_type]['logrotate_X']`
  - `node['defaults']['global']['logrotate_X']`
Only properties for which an explicit setting exists at one of these four levels will explicitly configured in the corresponding `logrotate_app` resource. Global defaults:
  * `logrotate_rotate`: 30
  * `logrotate_frequency`: `'daily'`
  * `logrotate_options`: `%w[missingok compress delaycompress notifempty copytruncate sharedscripts]`

### PR DESCRIPTION
**Pull request by nickmarden**
Fixes #107 

TODO:
- [ ] Add documentation about `logrotate_*` attribute behaviors
- [ ] Add integration tests

### CODE REVIEW

**Comment by nickmarden** [comment]
@phongsi @ajgon I realized that I made a conceptual mistake here - attribute override of `logrotate_log_paths` should not be an app `'global'` behavior; it should be overridden at the `'webserver'`, `'framework'`, etc. level. I think all of the other ideas in this PR are correct, but I'll need to fix this before this will be suitable for merging.

**Comment by phongsi** [comment]
i've closed my pr and issue. This looks more flexible and covers my use case.

**Comment by nickmarden** [comment]
OK, much better now. Three things that I discovered along the way to fixing things:

1. I had never actually activated my `maximum_override` integration test in `.travis.yml`. Eep! Fixed.
2. In order to properly tease apart webserver and framework logrotate configs, I needed to do quite a bit of surgery so that the attribute evaluation helpers could understand which driver context they were being executed in. This also allowed me to remove a bunch of copy-pasta code that involved the merging of `node['defaults']['something']` and `node['deploy'][app_name]['something']`, at the expense of a bunch of calls to `driver.driver_type`.
3. Attribute evaluation for logrotate settings was non-trivial and needed to be documented in several places in order to give people a chance at understanding it. ✔️

**Comment by nickmarden** [comment]
I force-pushed this, so I'll open a new PR.

**Pull request closed without merging**
