### PR TITLE
feat(ruby): Replace ruby-ng with rvm

### PR DESCRIPTION
**Pull request by kpheasey**
This change constitutes a major version bump.  It has not been included, but I can easily add it if you're in agreement about the necessity of the version bump.

There is one issue; if you don't specify a minor version number i.e. 2.3.x, it will break the setup.  The `/usr/local/bin` symlinks target the specific rvm directory which is named after the ruby version.

### CODE REVIEW

**Comment by ajgon** [comment]
Regarding the issue. I think the simple fix would be (when determining links for bundler) to invoke the `rvm list strings`, take the installed version name from there and use it when building symlink. I would really like to avoid forcing user to enter the release number, since mostly only major.minor version matters.

**Comment by kpheasey** [comment]
That sounds like a good plan.  If I get time this coming week, I'll try to implement.

**Comment by ajgon** [comment]
Great, thank you! Also please write in a commit message, that this is `BREAKING CHANGE` and `[ruby-ng][ruby_version]` parameter was replaced with `[rvm][default_ruby]`.

**Comment by kpheasey** [comment]
This has actually proven to be problematic.... The only reason I needed rvm was for debugging symbols, but I'm having tons of other issues related to permissions for who can install gems, write access, etc.  I'm going to close this, but I'll leave my branch up if anyone wants to experiment with it.

**Pull request closed without merging**
