### PR TITLE
feature(logrotate): pass script parameters into logrotate

### PR DESCRIPTION
**Pull request by phongsi**
[issue #105 ](https://github.com/ajgon/opsworks_ruby/issues/105)
This gives the user the ability to add postscript, prescript, etc. Also, will throw a no method error if the option is invalid. This defaults to an empty hash.

### CODE REVIEW

**Comment by nickmarden** [comment]
@phongsi I have a much more generalized approach to this for which I was about to open a PR. It allows you to override _any_ resource property of the `logrotate_app` resource, rather than just this one, using node attributes. I'll try to get it up here ASAP so that you can take a look and decide if it handles your case as well.

**Comment by nickmarden** [comment]
OK it's https://github.com/ajgon/opsworks_ruby/pull/108 if you wanna look.

**Comment by phongsi** [comment]
closing this as @nickmarden has a more robust solution

**Comment by nickmarden** [comment]
OK @phongsi I'll prioritize fixing up #108 today so that you can get that functionality ASAP.

**Pull request closed without merging**
