### PR TITLE
feat: support rails restart command on puma.

### PR DESCRIPTION
**Pull request by ruzia**
see also: https://github.com/puma/puma/blob/master/docs/plugins.md#plugins

### CODE REVIEW

**Comment by ajgon** [comment]
Why do you think it's necessary? You can always restart the app, using OpsWorks panel...

**Comment by ruzia** [comment]
Thanks for reply!
In case of emergency operation, I want to quickly restart from the terminal.

**Comment by interu** [comment]
Chef12 Stack does not seem to be able to restart on OpsWorks panel...

**Comment by ajgon** [comment]
Ok, I'm fine with that then - but plugins where introduced in puma 3.0. What about backwards compatibility?

**Comment by ajgon** [comment]
Merged.

**Pull request closed without merging**
